export { analizeDirection } from "./analizeDirection.js"
export { newBot } from "./newBot.js"
export { oppositeDirection } from "./oppositeDirection.js"
export { possibleDirections } from "./possibleDirections.js"
export { setBotMemory } from "./setBotMemory.js"